"""empty message

Revision ID: 84f491ea0559
Revises: 9e3341acbbda
Create Date: 2018-12-11 09:23:03.381000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '84f491ea0559'
down_revision = '9e3341acbbda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artefatoDono',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descricao')
    )
    op.create_table('artefatoTipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descricao')
    )
    op.drop_table('artefatotipo')
    op.drop_table('artefatodono')
    op.drop_constraint(u'artefato_ibfk_1', 'artefato', type_='foreignkey')
    op.drop_constraint(u'artefato_ibfk_2', 'artefato', type_='foreignkey')
    op.create_foreign_key(None, 'artefato', 'artefatoTipo', ['artefatoTipo_id'], ['id'])
    op.create_foreign_key(None, 'artefato', 'artefatoDono', ['artefatoDono_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artefato', type_='foreignkey')
    op.drop_constraint(None, 'artefato', type_='foreignkey')
    op.create_foreign_key(u'artefato_ibfk_2', 'artefato', 'artefatotipo', ['artefatoTipo_id'], ['id'])
    op.create_foreign_key(u'artefato_ibfk_1', 'artefato', 'artefatodono', ['artefatoDono_id'], ['id'])
    op.create_table('artefatodono',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('descricao', mysql.VARCHAR(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('artefatotipo',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('descricao', mysql.VARCHAR(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('artefatoTipo')
    op.drop_table('artefatoDono')
    # ### end Alembic commands ###
