"""empty message

Revision ID: 973878997608
Revises: c8eb2458b51b
Create Date: 2018-12-19 12:06:16.224000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '973878997608'
down_revision = 'c8eb2458b51b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insumo', sa.Column('codigoBEC', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insumo', 'codigoBEC')
    op.drop_constraint(None, 'artefato', type_='foreignkey')
    op.drop_constraint(None, 'artefato', type_='foreignkey')
    op.create_foreign_key(u'artefato_ibfk_2', 'artefato', 'artefatotipo', ['artefatoTipo_id'], ['id'])
    op.create_foreign_key(u'artefato_ibfk_1', 'artefato', 'artefatodono', ['artefatoDono_id'], ['id'])
    op.create_table('artefatodono',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('descricao', mysql.VARCHAR(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('artefatotipo',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('descricao', mysql.VARCHAR(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('artefatoTipo')
    op.drop_table('artefatoDono')
    # ### end Alembic commands ###
